### PR TITLE
Use SSE intrinsic instead of f32::sqrt()

### PR DESCRIPTION
**Pull request by Arvamer**
Can we assume that SSE is always present on x86?

### CODE REVIEW

**Comment by CryZe** [comment]
Only on x86-64 is SSE guaranteed.

**Comment by Arvamer** [comment]
I know about this. My question is more about if we should care about someone using Pentium II in 2019 :).

**Comment by CryZe** [comment]
In my opinion f32::sqrt should be used, as in the other issue it was already kind of considered that it doesn't make sense for this crate to support no_std anyway. I consider that even more unlikely than a CPU not supporting SSE in 2019.

**Comment by Arvamer** [comment]
Personally I don't have strong opinion about solving this issue, but removing support for `no_std` is probably the simplest one. I have another branch where it's implemented that I used for testing, so @Lokathor  feel free to close this PR, I can open another one with alternative solution.

**Comment by Lokathor** [comment]
@cryze it's not that you'll be maybe on intel without sse, it's that you can run windows on ARM these days too, and there's gonna be more of that going forward probably.

But sure, we can close this up

**Pull request closed without merging**
