### PR TITLE
GetStateEx support

### PR DESCRIPTION
**Pull request by Originalimoc**
Not Option<>, I believe this will never get removed

### CODE REVIEW

**Comment by Lokathor** [comment]
The code seems good. I'm not sure what you mean by "Not Option<>" though

**Comment by Originalimoc** [comment]
Existing code treat some external functions Option<T>, this one is not, meaning if loading Ordinal 100 failed the program panic.

**Comment by Lokathor** [comment]
If it's an Ex function that didn't exist in some early version of XInput, then it needs to be optionally loaded.

Using option or not is about compatibility back to old XInput versions, not a concern that the functions will go away in a future version.

**Comment by MaulingMonkey** [comment]
GetStateEx wasn't introduced until XInput 1.3.  It's also an undocumented function exported by ordinal only.
Steam, Origin, etc. use it however - so it's probably fairly safe to rely on.

* <https://docs.rs/thindx/0.0.0-unsound.5/thindx/xinput/index.html#functions>
* <https://learn.microsoft.com/en-us/windows/win32/xinput/xinput-versions>

**Pull request merged**
