### PR TITLE
Implement a non-global API.

### PR DESCRIPTION
**Pull request by jmgao**
Make it possible to load specific XInput DLLs by name by moving the
implementation from being reliant on a global handles to operations
on a struct that holds the handles. The existing APIs are left intact,
operating on a lazily initialized global handle.

Implements most of #12.

### CODE REVIEW

**Comment by jmgao** [comment]
I removed the atomic initialization stuff in the patch, because it didn't seem very useful to me. It feels like not be able to find any XInput DLL is basically unrecoverable, and even if the caller wants to try, we have no way to tell them when they should actually try again.

**Comment by Lokathor** [comment]
This is pretty good, but it still doesn't cover all the other functions, which I'd want to do before publishing it as a 2.0. However, it's also clearly breaking, so we can't put it out as a 1.1

I can accept it now if you want, and then add the other functions so that it can go out as a 2.0, or you're also invited 

for reference, I recently did a fresh xinput cleanup [in another project](https://github.com/Lokathor/thorium/blob/master/src/bin/win32_old/xinput.rs), so that has the complete list of all the xinput functions that we'd want to support.

**Comment by jmgao** [comment]
> This is pretty good, but it still doesn't cover all the other functions, which I'd want to do before publishing it as a 2.0. However, it's also clearly breaking, so we can't put it out as a 1.1

Do you mean that it's an observable behavioral change? I'm not sure there are any plausible ways to actually notice this (the only way I can think of that doesn't involve deleting a bunch of system DLLs is a bogus DLL next to your executable that disappears when you try to load again.

> I can accept it now if you want, and then add the other functions so that it can go out as a 2.0, or you're also invited to add the rest to the PR yourself.

Whatever's more convenient for you, I'm happy just vendoring my changes until you think this PR is good to merge.

I added wrappers for Enable, GetCapabilities, and GetKeystroke, but the audio stuff didn't have an obvious abstraction to me, since it looks like XInputGetDSoundAudioDeviceGuids was removed in Windows 8.

**Comment by Lokathor** [comment]
The observable change is that anyone who was using the previous version has to change their code. That's why you had to change the `example.rs` file, because the API of the crate is different.

I got scheduled for some extra stuff this week, but I'll try to accept this and perform final cleanup and have some sort of 2.0 version out by the end of the week if I can.

**Comment by jmgao** [comment]
Unless I missed a function, that shouldn't be the case: all of the old functions were replaced by a method call on a global lazy_static handle: e.g. https://github.com/Lokathor/rusty-xinput/pull/14/commits/71dfd67478f16dd6c05e46e821a7c7374f28f3ed#diff-b4aea3e418ccdb71239b96952d9cddb6R657

I changed example.rs to the new API because it's marginally faster.

**Pull request merged**
